CREATE TABLE [dbo].[Bids]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[ItemId] INT NOT NULL,
	[BidderId] INT NOT NULL,
	[BidAmount] DECIMAL(18, 2) NOT NULL,
	[IsWinning] BIT NOT NULL DEFAULT 0,
	[BidDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
	FOREIGN KEY (ItemId) REFERENCES AuctionItems(Id),
	FOREIGN KEY (BidderId) REFERENCES [User](Id)
)
