CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[FullName] NVARCHAR(256) NOT NULL,
	[Email] NVARCHAR(256) NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[IsActive] BIT NOT NULL DEFAULT 1

)
